import React from "react";
import { AbsoluteFill, Sequence } from "remotion";
import {
  Adjustment,
  AnimatedText,
  AudioTrack,
  Dissolve,
  Fade,
  Grade,
  LogoReveal,
  Mask,
  StillImage,
  SvgAnimation,
  Transform,
  VideoClip,
} from "../../src/components";

/**
 * Smoke test that exercises every component with throw-away media generated by
 * `npm run test:media` (written to temp/, which is git-ignored).
 */
const ComponentTest: React.FC = () => (
  <AbsoluteFill style={{ background: "#111" }}>
    <Sequence name="video" durationInFrames={60}>
      <Fade inFrames={10} outFrames={10}>
        <Grade saturation={1.3} contrast={1.1}>
          <VideoClip src="temp/test-pattern.mp4" trimBefore={15} />
        </Grade>
      </Fade>
    </Sequence>
    <Sequence name="image" from={30} durationInFrames={60}>
      <Dissolve frames={15}>
        <Mask mask={{ type: "inset", top: 10, right: 30, bottom: 10, left: 30, round: 24 }}>
          <StillImage src="temp/test-still.png" kenBurns={1.1} />
        </Mask>
      </Dissolve>
    </Sequence>
    <Sequence name="svg" durationInFrames={90}>
      <Transform keyframes={[{ frame: 0, y: -200, scale: 0.6 }, { frame: 60, y: -220, scale: 0.7 }]}>
        <SvgAnimation src="generated/svg/example-draw-v01.svg" width={600} drawFrames={30} />
      </Transform>
    </Sequence>
    <Sequence name="text" durationInFrames={90}>
      <Transform y={220}>
        <AnimatedText text="Component test" animation="words" style={{ fontSize: 56 }} />
      </Transform>
    </Sequence>
    <Sequence name="logo" from={45} durationInFrames={45}>
      <Transform x={380} y={-260} scale={0.4}>
        <LogoReveal src="assets/logos/placeholder-logo.svg" style="blur" />
      </Transform>
    </Sequence>
    <Sequence name="audio" durationInFrames={90}>
      <AudioTrack src="temp/test-tone.wav" volume={0.5} fadeInFrames={10} fadeOutFrames={20} />
    </Sequence>
    <Adjustment vignette={0.5} grain={0.15} letterbox={40} />
  </AbsoluteFill>
);

export default ComponentTest;
